function run(){
    var search = document.getElementById('input_field').value;

    //alert(search);

    const options = {
    method: 'POST',
    headers: {
        'content-type': 'application/json',
        'X-RapidAPI-Key': 'c3e7e0f9a2msh9541025fef72972p19b90ejsn2b4a44807bbe',
        'X-RapidAPI-Host': 'chatgpt-ai-chat-bot.p.rapidapi.com'
    },
    body: '{"text":"'+search+'"}'
    };
    
    fetch('https://chatgpt-ai-chat-bot.p.rapidapi.com/ask', options)
    .then(response => response.text())
    .then(response =>  boxvalue = document.getElementById('input_field1').value = response )
    .catch(err => boxvalue = document.getElementById('input_field1').value = console.error(err));
}



///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  -------------> This Function is to Copy The Text Results Generated by The AI. <------------

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

function myFunction() {
    // Get the text field
    var copyText = document.getElementById("input_field1");
  
    // Select the text field
    copyText.select();
    copyText.setSelectionRange(0, 99999); // For mobile devices
  
    // Copy the text inside the text field
    navigator.clipboard.writeText(copyText.value);
    
    // Alert the copied text
   // alert("Copied the text: " + copyText.value);
   var cpy_txt = copyText.value;
  }


  
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  -------------> This Function is to Conver Text to PDF, Generated by The AI. <------------

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// function pdf_wala() {
//     var doc = new jsPDF()
//     src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"
//     //doc.text('Hello world!', 10, 10) 
//     doc.text(cpy_txt, 10, 10) 
//     doc.save('a4.pdf')
//   }
